model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
[projects."/home/shinjungtae/Projects/Blackcircles/kubernetes-helm-charts"]
trust_level = "trusted"

[projects."/home/shinjungtae/Projects/Personal/xv6-riscv"]
trust_level = "trusted"

[projects."/home/shinjungtae/Projects/Blackcircles/ml/blackcircles-ml-workflows"]
trust_level = "trusted"

[projects."/home/shinjungtae/.config/opencode"]
trust_level = "trusted"

[projects."/home/shinjungtae/Projects/Blackcircles/platform/idp-be"]
trust_level = "trusted"

[projects."/home/shinjungtae"]
trust_level = "untrusted"

[projects."/home/shinjungtae/Projects/Blackcircles/infra/blackcircles-infrastructures"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp"]

[mcp_servers.kubernetes]
command = "/home/shinjungtae/mcp-servers/kubernetes-mcp-server/k8s-mcp-server"

[mcp_servers.terraform]
command = "/home/shinjungtae/mcp-servers/terraform-mcp-server/terraform-mcp-server"

[mcp_servers.aws-serverless]
command = "/home/shinjungtae/mcp-servers/venv/bin/awslabs.aws-serverless-mcp-server"

[mcp_servers.iam-blackcircles-develop]
command = "uvx"
args = ["awslabs.iam-mcp-server@latest"]

  [mcp_servers.iam-blackcircles-develop.env]
  AWS_PROFILE = "blackcircles-develop"
  AWS_REGION = "ap-northeast-2"

[mcp_servers.iam-blackcircles-prod-readonly]
command = "uvx"
args = ["awslabs.iam-mcp-server@latest", "--readonly"]

  [mcp_servers.iam-blackcircles-prod-readonly.env]
  AWS_PROFILE = "blackcircles-prod"
  AWS_REGION = "ap-northeast-2"

[mcp_servers.iam-tirepick]
command = "uvx"
args = ["awslabs.iam-mcp-server@latest"]

  [mcp_servers.iam-tirepick.env]
  AWS_PROFILE = "tirepick"
  AWS_REGION = "ap-northeast-2"

[mcp_servers.iam-control-plane]
command = "uvx"
args = ["awslabs.iam-mcp-server@latest"]

  [mcp_servers.iam-control-plane.env]
  AWS_PROFILE = "control-plane"
  AWS_REGION = "ap-northeast-2"
