# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FFFFFF)
$foreground = rgb(343E55)
$color0 = rgb(FFFFFF)
$color1 = rgb(A39FA5)
$color2 = rgb(B4B1B8)
$color3 = rgb(B0AEB6)
$color4 = rgb(919FB2)
$color5 = rgb(747F9C)
$color6 = rgb(56688E)
$color7 = rgb(343E55)
$color8 = rgb(AAA7AC)
$color9 = rgb(DAD5DC)
$color10 = rgb(F0ECF5)
$color11 = rgb(EBE8F2)
$color12 = rgb(C2D4EE)
$color13 = rgb(9BA9CF)
$color14 = rgb(738ABE)
$color15 = rgb(11151C)
