# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B4CBFD
background         #101116
cursor             #5E76CB

active_tab_foreground     #101116
active_tab_background     #B4CBFD
inactive_tab_foreground   #B4CBFD
inactive_tab_background   #101116

active_border_color   #B4CBFD
inactive_border_color #101116
bell_border_color     #061973

color0      #38393E
color1		#061973
color2		#061973
color3		#1E4FBC
color4		#1E4FBC
color5		#1E4FBC
color6		#1E50BC
color7		#8BACF4
color8		#6178AB
color9		#082299
color10		#082299
color11		#286AFA
color12		#286AFA
color13		#286AFA
color14		#286AFA
color15		#8BACF4
