# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #343E55
background         #FFFFFF
cursor             #9295A5

active_tab_foreground     #FFFFFF
active_tab_background     #343E55
inactive_tab_foreground   #343E55
inactive_tab_background   #FFFFFF

active_border_color   #343E55
inactive_border_color #FFFFFF
bell_border_color     #A39FA5

color0      #FFFFFF
color1		#A39FA5
color2		#B4B1B8
color3		#B0AEB6
color4		#919FB2
color5		#747F9C
color6		#56688E
color7		#343E55
color8		#AAA7AC
color9		#DAD5DC
color10		#F0ECF5
color11		#EBE8F2
color12		#C2D4EE
color13		#9BA9CF
color14		#738ABE
color15		#11151C
