# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User window/layer rules entrypoint
source = $HOME/.config/hypr/configs/WindowRules.conf

# Zed editor opacity (active inactive)
windowrule = match:class ^(dev.zed.Zed)$, opacity 0.9 0.8